# Add your funding links below. Uncomment/edit as needed.
# github: ElementAstro
# patreon: your-patreon-name
# open_collective: lithium-next
# ko_fi: your-kofi-name
# custom:
#   - https://afdian.net/a/elementastro
