name: Feature Request
description: Suggest an idea or enhancement for Lithium-Next
labels:
  - enhancement
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping us improve Lithium-Next! Please provide as much detail as possible.
  - type: input
    id: summary
    attributes:
      label: Summary
      description: Concise title of the feature
      placeholder: e.g. Support new focuser driver
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Motivation / Problem
      description: What problem does this feature solve? Why is it important?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed Solution
      description: How would you like to see this implemented? Include UI/UX, API, or CLI details if applicable.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other approaches did you consider?
    validations:
      required: false
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Links, references, screenshots, or anything else helpful.
    validations:
      required: false
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have checked that this feature does not already exist
          required: true
        - label: I am willing to help with development
          required: false
